version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: wp_docker_mysql
    restart: on-failure:5
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    container_name: wp_docker_wordpress
    restart: on-failure:5
    ports:
      - 80:80
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    environment:
      DB_HOST: mysql:3306
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_NAME: wordpress

volumes:
  db_data: {}
