version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: wp_docker_mysql
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure:5
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mysql
    image: wordpress:5.2.4-php7.2
    container_name: wp_docker_wordpress
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
    restart: on-failure:5
    environment:
      DB_HOST: mysql:3306
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_NAME: wordpress

volumes:
  db_data: {}
